test: "完成了"

spring:
   neo4j:
      url: bolt://localhost:7687
      username: neo4j
      password: 123456
   datasource:
      name: test
      url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/digital_thread?useUnicode=true&characterEncoding=UTF8&serverTimezone=UTC
      username: root
      password: 123456
# 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat,wall,slf4j
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
#rabbitmq:刷新配置访问的方式 http://localhost:8600/actuator/bus-refresh
   rabbitmq:
      host: localhost
      port: 5674
      username: guest
      password: guest
management:
   endpoints:
      web:
         exposure:
            include: "*"
mybatis:
   basepackage: com.je.digital.thread.system.mapper
   xmlLocation: classpath:mapper/**/*.xml
   mapper-locations: classpath*:mapper/*.xml
