test: 6676666

spring:
#rabbitmq:刷新配置访问的方式 http://localhost:8600/actuator/bus-refresh
   rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
management:
   endpoints:
      web:
         exposure:
            include: "*"
